version: '3.2'
services:
  mysqldb:
    image: mysql:5.7
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DBNAME
      ports:
        3306:3306
    volumes:
        - ./sql:/docker-entrypoint-initdb.d
  app:
    image: john/express-backend
    ports:
           -  3000:3000
    depends_on:
      - mysqldb
    stdin_open: true
    tty: true
    container_name: express-backend-app
    command: /bin/bash -c "npm install && npm start"